name: Pull Requests
on: pull_request

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: '[build] generate rmf msgs'
        uses: ./.github/actions/gen-rmf-msgs
      - name: '[build] npm package'
        run: npm run build:package
      - name: test
        run: npm run test && npm run test:browser
